# Site settings
# http://stevenmaguire.com.s3-website-us-east-1.amazonaws.com
title: Steven Maguire
email: "&#115;&#116;&#101;&#118;&#101;&#110;&#109;&#097;&#103;&#117;&#105;&#114;&#101;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
description: >
  Builder of Teams, Software Architect, and Product Designer living in Chicago, IL
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stevenmaguire.com"
enforce_ssl: stevenmaguire.com

logo_color: https://s3.amazonaws.com/static.stevenmaguire.com/logo.png
logo_white: https://s3.amazonaws.com/static.stevenmaguire.com/logo-white.png
logo_label: https://s3.amazonaws.com/static.stevenmaguire.com/logo-steven-maguire.png

google_analytics_id: "UA-1132651-2"
drift_token: "6danw8e5uan3"

twitter_username: stevenmaguire
github_username: stevenmaguire

emptyArray: []

birthdate: 2015-11-25 12:00:00

# Build settings!
markdown: kramdown

packagist_stats_url: https://8ejchx5m9h.execute-api.us-west-2.amazonaws.com/prod/getOpenSourceDownloads

stats:
  opensource_downloads: 359782

collections:
  logos:
  opensource:
  publications:
    output: true
  projects:
  theatre:
  volunteering:


